### ISSUE TITLE
Intermittent crashes - onProgress()

### ISSUE THREAD

**Issue by AlexanderHearX** [brownsoo/ValueAnimator#2]
Hi,

I sometimes get crashes when animating a value. bad exec error at onProgress() method

Firebase crash report:

CoreFoundation
-[NSOrderedSet initWithSet:copyItems:]

The requirements to reproduce the error is unknown. 

Breakpoint:
while aniList.count > 0  //line 256 on ValueAnimator.swift

It's got something to do with aniList set

**Comment by brownsoo** [comment]
Thank you for report. It seems the error occurs on inserting new item during processing the 'aniList'  in 'onProgress'.  I fixed and updated. please try to update cocoapods.

**Comment by AlexanderHearX** [comment]
Hi is there a fix for this?

**Comment by brownsoo** [comment]
Wow, I am in uploading codes .. please wait, Sorry.

**Comment by brownsoo** [comment]
I updated cocoapods 0.6.0~
I hope this update to fix the 'crashes - onProgress'.
