### ISSUE TITLE
animate의 onChanged

### ISSUE THREAD

**Issue by ParkHayoung** [brownsoo/ValueAnimator#5]
안녕하세요. 좋은 라이브러리 감사드립니다.

animate의 onChaned 에서
value값 대신 애니메이션의 진척률을 알아올 순 없나요?

**Comment by brownsoo** [comment]
반복 동작도 있어서 진척률을 일률적으로 반영하기가 어렵구요. 경과시간값을 외부로 노출시켜서 애니메이션 시간으로 나눌 수 있게 하면 어떨까요? 

경과시간값은 코드를 수정해서 업데이트 해야 가능합니다. 좋은 의견같아요. 빨리 업데이트하고 코멘트 달겠습니다.

**Comment by brownsoo** [comment]
@ParkHayoung 진척률을 확인할 수 있도록 업데이트를 좀 했습니다. 소스를 업데이트하고 예제를 살펴보세요.
이런 식으로 경과시간을 계산할 수 있도록 했습니다.

`let progress = ani.covered / ani.duration`
