### ISSUE TITLE
Xcode 12 GM version issue

### ISSUE THREAD

**Issue by ParkHayoung** [brownsoo/ValueAnimator#6]
![image](https://user-images.githubusercontent.com/20125482/93315434-0431e780-f846-11ea-9d85-226fc0f76c03.png)

안녕하세요. xcode 12 gm 버전 관련해서 문의드립니다.
해당 버전으로 빌드를 돌렸는데, 위와 같이 컴파일 에러가 발생합니다.
라이브러리 버전을 업데이트 해도 동일한 증상 발생하구요.
확인 부탁드리겠습니다. 감사합니다.

**Comment by brownsoo** [comment]
안녕하세요. XCode 12버전에서는 빌드를 안 해봤는데, 설치해서 확인해봐야 겠습니다.감사합니다!

**Comment by brownsoo** [comment]
@ParkHayoung Xcode 12버전으로 해당 부분 확인해서 업데이트 했습니다. 왜.. 저기 부분만 타입 체크 오류가 나는지 모르겠네요. 컴파일러에 문제가 있어보이네요. pod를 0.6.4로 다시 받아서 해보시겠어요?

**Comment by ParkHayoung** [comment]
확인했습니다. 감사합니다! 👍🏻👍🏻
