### ISSUE TITLE
SPM Install Issue

### ISSUE THREAD

**Issue by salubhayo** [brownsoo/ValueAnimator#9]
Getting Issue while installing Value Animator through SPM

<img width="678" alt="Screen Shot 2022-08-19 at 11 24 58" src="https://user-images.githubusercontent.com/77044150/185566591-6c854bd4-0c69-45a8-928f-f44680a652af.png">

**Comment by brownsoo** [comment]
@salubhayo Hello, I am sorry to see your report lately. I will care this issue asap.

**Comment by brownsoo** [comment]
@salubhayo i updated source structure for SPM. please try again../ thank you.
